### ISSUE TITLE
Incomplete contextualization for narrow Tibetan above-base vowels

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tibetan#14]
### Font
NotoSerifTibetan-Regular.otf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/b7dab18090b095dc82f1db789abd81a8e4b322ad/unhinted/otf/NotoSerifTibetan/NotoSerifTibetan-Regular.otf
Date: 2022-03-01

### Font version
Version 2.101

### Issue
When two adjacent clusters, possibly with an intervening tsheg, have above-base marks, the marks sometimes take narrow forms, but they are inconsistent about it.

If there is a tsheg and the first cluster has two above-base marks and the second has only one, the marks are not narrowed. The first example string shows the correct narrowing when the second cluster has two marks. The second example string shows the incorrect rendering without narrow marks.

If there is no tsheg and the first cluster has two above-base marks, the first mark is not narrowed. The third and fourth example strings show the resulting overlap.

### Character data
ཐོྀ་ངཽེ
U+0F50 TIBETAN LETTER THA
U+0F7C TIBETAN VOWEL SIGN O
U+0F80 TIBETAN VOWEL SIGN REVERSED I
U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG
U+0F44 TIBETAN LETTER NGA
U+0F7D TIBETAN VOWEL SIGN OO
U+0F7A TIBETAN VOWEL SIGN E
ཐོྀ་ངོ
U+0F50 TIBETAN LETTER THA
U+0F7C TIBETAN VOWEL SIGN O
U+0F80 TIBETAN VOWEL SIGN REVERSED I
U+0F0B TIBETAN MARK INTERSYLLABIC TSHEG
U+0F44 TIBETAN LETTER NGA
U+0F7C TIBETAN VOWEL SIGN O
ཐོྀ་ངཽེ
U+0F50 TIBETAN LETTER THA
U+0F7C TIBETAN VOWEL SIGN O
U+0F80 TIBETAN VOWEL SIGN REVERSED I
U+0F44 TIBETAN LETTER NGA
U+0F7D TIBETAN VOWEL SIGN OO
U+0F7A TIBETAN VOWEL SIGN E
ཐོྀངོ
U+0F50 TIBETAN LETTER THA
U+0F7C TIBETAN VOWEL SIGN O
U+0F80 TIBETAN VOWEL SIGN REVERSED I
U+0F44 TIBETAN LETTER NGA
U+0F7C TIBETAN VOWEL SIGN O

### Screenshot
![ཐོྀ་ངཽེ␤ཐོྀ་ངོ␤ཐོྀངཽེ␤ཐོྀངོ](https://user-images.githubusercontent.com/1124347/156419649-f1ca7d94-efed-4d6d-8141-154c612a551d.png)

**Comment by SKing-2003** [comment]
Does this look better in your eyes?
![image](https://user-images.githubusercontent.com/107930743/175957579-53d591eb-2d1f-43b0-b66b-66bcbd71e21d.png)

**Comment by dscorbett** [comment]
Yes. The inconsistency seems to have been fixed. Some sequences still overlap (e.g. ⟨ཐོྀངཽེ⟩) but I can open a different issue for that.

**Comment by SKing-2003** [comment]
Thank you!
