### ISSUE TITLE
Noto Serif Tibetan glyphs and line height too large?

### ISSUE THREAD

**Issue by josephrocca** [notofonts/tibetan#23]
### Font 
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://fonts.google.com/download?family=Noto%20Serif%20Tibetan
Date: 2022-05-06

[Noto_Serif_Tibetan.zip](https://github.com/googlefonts/noto-fonts/files/8641192/Noto_Serif_Tibetan.zip)

### Font Version
2.001

### OS name and version
Ubuntu 20.04

### Application name and version
Chrome Linux v100

### Issue
The glyphs and line height are significantly larger than two other Tibetan fonts that I tested at the same specified font size.

Here's an example comparing it to the 'Jomolhari' font:

https://jsbin.com/zicanemivi/edit?html,output

### Character data

Just some example text: ༝ འགབམ

### Screenshot

![image](https://user-images.githubusercontent.com/1167575/167144982-249b9f2e-2b7d-4192-86c0-91119e4dfee8.png)

**Comment by simoncozens** [comment]
I don't think this is a problem. I'd say that conversely the glyphs in Jomolhari are too small, especially when you look at them in relationship to the Latin glyphs as in your example.

**Comment by josephrocca** [comment]
@simoncozens Fair, but are you sure it needs all that line height?

**Comment by simoncozens** [comment]
Yes, because of the (high) possibility of stacking. At any rate, we set vertical metrics according to our [best practices guide](https://googlefonts.github.io/gf-guide/metrics.html).
