### ISSUE TITLE
U+0F39 TIBETAN MARK TSA -PHRU blocks ligatures

### ISSUE THREAD

**Issue by dscorbett** [notofonts/tibetan#7]
### Font
NotoSerifTibetan-Regular.ttf

### Where the font came from, and when
Site: https://github.com/googlefonts/noto-fonts/blob/96e3d51ab4ad78e74a4cb0752dc25d010d6946de/unhinted/NotoSerifTibetan/NotoSerifTibetan-Regular.ttf
Date: 2020-01-02

### Font version
Version 2.001

### Issue
U+0F39 TIBETAN MARK TSA -PHRU blocks ligatures.

### Character data
དུ༹ར༹ྦཋ༹ྲ
U+0F51 TIBETAN LETTER DA
U+0F39 TIBETAN MARK TSA -PHRU
U+0F74 TIBETAN VOWEL SIGN U
U+0F62 TIBETAN LETTER RA
U+0F39 TIBETAN MARK TSA -PHRU
U+0FA6 TIBETAN SUBJOINED LETTER BA
U+0F4B TIBETAN LETTER TTHA
U+0F39 TIBETAN MARK TSA -PHRU
U+0FB2 TIBETAN SUBJOINED LETTER RA

### Screenshot
![དུ༹ར༹ྦཋ༹ྲ](https://user-images.githubusercontent.com/1124347/72083794-635f5580-32d0-11ea-9a58-52de699892ea.png)

**Comment by simoncozens** [comment]
I'm seeing broken clusters in your example text, suggesting that TSA PHRU doesn't really want to go there. Should it go after the subjoined things instead? (དུ༹རྦ༹ཋྲ༹ has no dotted circles.)

**Comment by dscorbett** [comment]
Are you testing with HarfBuzz?

**Comment by simoncozens** [comment]
Ah, right. Harfbuzz is reordering, Safari/CoreText is not:

<img width="154" alt="Screenshot 2022-09-16 at 17 46 21" src="https://user-images.githubusercontent.com/106728/190689012-2a8d681e-c5c2-41dc-89cd-3ccba8780a6f.png">

I don't know if that's relevant for the issue anyway.

**Comment by dscorbett** [comment]
In the first cluster, U+0F74 TIBETAN VOWEL SIGN U and U+0F39 TIBETAN MARK TSA -PHRU have different canonical combining classes, so their relative order should not matter.

In the last two clusters, the tsa ’phru follows the head consonant and precedes the subjoined consonant. <i>The Unicode Standard, Version 15.0</i> says “Where used, the character U+0F39 TIBETAN MARK TSA -PHRU occurs immediately after the consonant it modifies.” I don’t know if it ever modifies these particular head consonants, but in principle, it is allowed to precede a subjoined consonant.

Therefore, Core Text is wrong.

**Comment by simoncozens** [comment]
I think this is now fixed; I'm getting the TSA -PHRU's on the ligatures:
![shape](https://user-images.githubusercontent.com/106728/234830861-786b1541-eda4-4e3c-ac2d-1b8b1ff590e7.png)
